### ISSUE TITLE
I got an error in download the course 

### ISSUE THREAD

**Issue by Carlosx7** [shihabmridha/educative.io-downloader#1]
Thank, bro! It is very awsome!
These are some error message when i started the program.
![TIM截图20200131160208](https://user-images.githubusercontent.com/3402621/73522410-4dfac880-4443-11ea-9cca-07b936d1aeef.jpg)

**Comment by shihabmridha** [comment]
Thank you for trying it out. I am sorry to say that I do not really understand the error. I tried to use it in windows and it ran without any issue.

**Possible issue:**
It might be an issue with your NodeJS installation. Also, do not forget to compile the TS first.

**Comment by Carlosx7** [comment]
Thank you for your reply.I follow the step but still have error

`
CarlosdeMac-mini:educative.io-downloader carloswong$ npm run compile

> educative.io-downloader@1.0.0 compile /Users/carloswong/educative.io-downloader
> tsc -p .

CarlosdeMac-mini:educative.io-downloader carloswong$ npm start

> educative.io-downloader@1.0.0 start /Users/carloswong/educative.io-downloader
> node build/src/app.js

Loggin in.
Download in proguress. Course URL => https://www.educative.io/courses/docker-for-developers
Navigation timeout of 30000 ms exceeded
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! educative.io-downloader@1.0.0 start: `node build/src/app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the educative.io-downloader@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/carloswong/.npm/_logs/2020-01-31T08_26_42_455Z-debug.log
`

**Comment by shihabmridha** [comment]
Did you forget to update `config/default.json` file?

**Comment by Carlosx7** [comment]
Thank you ! I had found the problem, Because I used network proxy. Now It works.
