### ISSUE TITLE
Add support for animated slides

### ISSUE THREAD

**Issue by devKshitijJain** [shihabmridha/educative.io-downloader#10]
https://www.educative.io/courses/coderust-hacking-the-coding-interview/k5llE

**Comment by devKshitijJain** [comment]
We can get the length of of slides present using `document.getElementsByClassName("Button-ktk5iw-0 CircleButton-f4i43u-0 styles__AnimationPlus-sc-2az9w3-13 dqWxjg").length` and then we need to call `document.getElementsByClassName("Button-ktk5iw-0 CircleButton-f4i43u-0 styles__AnimationPlus-sc-2az9w3-13 dqWxjg")[index].click();`. We can have a forloop to toggle multiple elements if present. These are the javascript functions, we need to figure out how to do it with pupeteer.

**Comment by devKshitijJain** [comment]
@shihabmridha

**Comment by devKshitijJain** [comment]
@shihabmridha raising PR

**Comment by shihabmridha** [comment]
Fixes https://github.com/shihabmridha/educative.io-downloader/pull/11
