### ISSUE TITLE
Image Functionality Broken

### ISSUE THREAD

**Issue by devKshitijJain** [shihabmridha/educative.io-downloader#12]
The changes I added broke the image functionality. Throwing error Protocol error (Page.captureScreenshot): Cannot take screenshot with 0 width. So we need to rethink the approach or I will suggest to stick to just HTML as code will be trimmed in both image and pdf.

**Comment by shihabmridha** [comment]
Yes, we can get rid of the image format.

**Comment by devKshitijJain** [comment]
@shihabmridha how about pdf?  Code will be trimmed in it too.

**Comment by shihabmridha** [comment]
I would like to keep it. Because, it is mostly readable.

**Comment by shihabmridha** [comment]
Fixes 1dd0c5b3c387b64f5efbf2f45abd33f27f4d4a32
