### ISSUE TITLE
new to typescript

### ISSUE THREAD

**Issue by KamaljeetMallik07** [shihabmridha/educative.io-downloader#16]
Sir,could you be more detailed?i am new to typescript as well as git

**Comment by shihabmridha** [comment]
Can you please specify what issue you are having? Is it about installing the script or downloading course?

**Comment by KamaljeetMallik07** [comment]
![Screenshot (120)](https://user-images.githubusercontent.com/63553543/80302474-ea750280-87c7-11ea-9848-cb7b576ebaee.png)

**Comment by KamaljeetMallik07** [comment]
how can i fix this error,sir?

**Comment by shihabmridha** [comment]
Run this command (`npm install -g typescript`) to install typescript globally. Then try again.

**Comment by KamaljeetMallik07** [comment]
Thank you,sir..
![Screenshot (122)](https://user-images.githubusercontent.com/63553543/80302883-535d7a00-87ca-11ea-92d2-6112b6d47b02.png)
![Screenshot (121)](https://user-images.githubusercontent.com/63553543/80302888-58bac480-87ca-11ea-924c-5ac94f085df3.png)
now I am getting error on "npm start" command

**Comment by shihabmridha** [comment]
When you ran `npm install` it should download chromium driver. As I see your log, it seems like chromium was not downloaded for some reason.

You can run `npm update`. It might download the chrome driver. If it doesn't then try removing **node_modules** directory and running `npm install` again.

**Comment by KamaljeetMallik07** [comment]
Thankyou soo much sir..

**Comment by KamaljeetMallik07** [comment]
![Screenshot (124)](https://user-images.githubusercontent.com/63553543/80306285-fec4f980-87df-11ea-9a60-708cbc0edfd2.png)
Sir,Why this error now?while downloading?is there any content losses?

**Comment by shihabmridha** [comment]
Either you are not logged in or you do not have access to the course.

**Comment by KamaljeetMallik07** [comment]
![Screenshot (125)](https://user-images.githubusercontent.com/63553543/80306431-e6091380-87e0-11ea-97cb-3d28956d133b.png)
Sir,here it is showing that i am logged in..
Then how come?

**Comment by KamaljeetMallik07** [comment]
![Screenshot (126)](https://user-images.githubusercontent.com/63553543/80306496-5879f380-87e1-11ea-9e7d-9877ea9db6d0.png)
And i do have the access to the course

**Comment by shihabmridha** [comment]
I see. Can you please follow this:
- Open browser.ts. Go to line 10 and make headless: false
- Run `npm run compile` to compile the change
- Then `npm start` to see how it behaves in browser

**Comment by KamaljeetMallik07** [comment]
![Screenshot (127)](https://user-images.githubusercontent.com/63553543/80306836-5dd83d80-87e3-11ea-9a3f-4f036367bb31.png)
This error i got while i ran "npm star"
now,what i need to do,sir?

**Comment by shihabmridha** [comment]
It wil be `npm start`. My bad.

**Comment by KamaljeetMallik07** [comment]
![Screenshot (128)](https://user-images.githubusercontent.com/63553543/80307005-2cac3d00-87e4-11ea-93bc-daed3089850b.png)
i got this

**Comment by KamaljeetMallik07** [comment]
Sir,what i need to do now?

**Comment by KamaljeetMallik07** [comment]
![Screenshot (129)](https://user-images.githubusercontent.com/63553543/80307317-df30cf80-87e5-11ea-8b9a-e20cf75bee94.png)
Sir, now its going on like this..

**Comment by KamaljeetMallik07** [comment]
i think its working on second time

**Comment by KamaljeetMallik07** [comment]
It worked thankyou so much,sir for your valuable time?
