### ISSUE TITLE
CSS Snippets are not visible

### ISSUE THREAD

**Issue by devKshitijJain** [shihabmridha/educative.io-downloader#18]
<img width="985" alt="Screenshot 2020-04-28 at 2 35 49 PM" src="https://user-images.githubusercontent.com/13154652/80469059-aae01f00-895d-11ea-9d8a-6be701fea070.png">

**Comment by shihabmridha** [comment]
Fixes https://github.com/shihabmridha/educative.io-downloader/pull/19
