### ISSUE TITLE
Seems like educative.io captcha is not working

### ISSUE THREAD

**Issue by arjunsreepad** [shihabmridha/educative.io-downloader#27]
❯ npm run compile

> educative.io-downloader@1.0.0 compile /Users/arjun/lab/educative/educative.io-downloader
> tsc -p .

error TS6047: Argument for '--target' option must be 'ES3', 'ES5', or 'ES6'.
error TS5023: Unknown compiler option 'lib'.
error TS5023: Unknown compiler option 'moduleResolution'.
error TS5023: Unknown compiler option 'noUnusedLocals'.
error TS5023: Unknown compiler option 'noUnusedParameters'.
error TS5023: Unknown compiler option 'forceConsistentCasingInFileNames'.
error TS5023: Unknown compiler option 'skipLibCheck'.
error TS5023: Unknown compiler option 'pretty'.
error TS5023: Unknown compiler option 'allowUnreachableCode'.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! educative.io-downloader@1.0.0 compile: `tsc -p .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the educative.io-downloader@1.0.0 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/arjun/.npm/_logs/2020-05-01T21_30_28_161Z-debug.log

**Comment by shihabmridha** [comment]
Which version of TypeScript are you using? Make sure you have the latest version installed.
Tested in: `3.8.3`

**Comment by arjunsreepad** [comment]
its solved. issue with Visual Code.
But now seems like educative.io captcha is not working

**Comment by shihabmridha** [comment]
@arjunsreepad Can you give us any update or insight?

**Comment by shihabmridha** [comment]
Duplicate https://github.com/shihabmridha/educative.io-downloader/issues/37
