### ISSUE TITLE
Login Functionality Broken

### ISSUE THREAD

**Issue by devKshitijJain** [shihabmridha/educative.io-downloader#29]
<img width="1074" alt="Screenshot 2020-05-05 at 3 33 59 PM" src="https://user-images.githubusercontent.com/13154652/81055239-eb074a80-8ee5-11ea-9ac1-0033eaa0e227.png">

**Comment by kodlan** [comment]
yeap I have the same issue

**Comment by kodlan** [comment]
Okay I was able to fix this locally, but I'm to lazy to create a PR.
Maybe the author will to that.

So to fix this go to src/login.ts and replace this two lines
  await page.type('#loginform-email', EMAIL);
  await page.type('#loginform-password', PASSWORD);

with this two lines
  await page.type('[name=email]', EMAIL);
  await page.type('[name=password]', PASSWORD);

**Comment by shihabmridha** [comment]
@kodlan I really wonder why using ID is not working but using name is working!

**Comment by kodlan** [comment]
well, there is no id there, I guess they removed it just recently

**Comment by shihabmridha** [comment]
@kodlan, Ah I see. Thanks 👍
