### ISSUE TITLE
Not getting logged in

### ISSUE THREAD

**Issue by devKshitijJain** [shihabmridha/educative.io-downloader#3]
`{
    "errorText": "Access denied. Please contact support@educative.io",
    "request_id": "5e6e09ac00ff0600ffa5a4c6439e0001737e6564756361746976652d6865736976650001763230303330322d686f746669782d3230303330392d3132313600010101"
}`

Also it shouldn't proceed downloading course if login failed

**Comment by devKshitijJain** [comment]
Any reason for closing this?

**Comment by shihabmridha** [comment]
Pushed a commit. See this: https://github.com/shihabmridha/educative.io-downloader/commit/e23d6c0af42ff3b3890758974739f3c6eec7a22c
