### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by arjunsreepad** [shihabmridha/educative.io-downloader#37]
I believe recently educative has enhanced the captcha

**Comment by aashish1910** [comment]
C:\Users\Aashish\Desktop\educative.io\educative.io-downloader>npm run install
npm ERR! missing script: install

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Aashish\AppData\Roaming\npm-cache\_logs\2020-05-07T04_24_18_631Z-debug.log

I am not to run npm run install. What should I do?

**Comment by devKshitijJain** [comment]
You need to change headless to false is browser.ts and see what's happening

**Comment by shihabmridha** [comment]
Don't have enough info.
