### ISSUE TITLE
Not able to run npm run install

### ISSUE THREAD

**Issue by aashish1910** [shihabmridha/educative.io-downloader#38]
C:\Users\Aashish\Desktop\educative.io\educative.io-downloader>npm run install
npm ERR! missing script: install

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Aashish\AppData\Roaming\npm-cache\_logs\2020-05-07T04_24_18_631Z-debug.log

Below is my Scripts tag in package.json
 "scripts": {
    "start": "node build/src/app.js",
    "dev": "nodemon build/src/app.js",
    "compile": "tsc -p .",
    "test": "echo \"Error: no test specified\" && exit 1",
  },

Can you please guide me step by step. I am a newbie...!

**Comment by devKshitijJain** [comment]
make `headless = false` in `browser.ts` file, then `npm run compile` and `npm start`. Then look what's the issue and post here.

**Comment by aashish1910** [comment]
It is false already. I am using in Windows 10. It will run on it?

async function launchBrowser(args?: object) {
  let configuration = {
    userDataDir: ROOT_PATH + '/data',
    headless: false
  };

**Comment by devKshitijJain** [comment]
Okay then try making it true. Its like the user agent that was added make issue when you run in headless=false mode. If sti it doesn't work then let us know.

**Comment by devKshitijJain** [comment]
try `npm install` instead of `npm run install`

**Comment by aashish1910** [comment]
If I have a subscription of one month and have access to all courses, then can I download each and every course?
Thanks for guiding me above.

**Comment by devKshitijJain** [comment]
Yes. Just make `downloadAllCourses = true` in default.json file and start script.

**Comment by devKshitijJain** [comment]
You may need to keep checking the files it generates. Sometimes it log you out and tool will keep downloading blank pages. So keep checking every last file in downloaded folder and track back if you see any blank file. We will fix the issue in future. Also some chapters or download may fail to download, so just re-run the tool again.

**Comment by devKshitijJain** [comment]
If you see blank files are being generated just hit ctrl+c in terminal to stop process, delete blank files and re-run the tool

**Comment by aashish1910** [comment]
Bhaiya, I am thinking of buying the subscription for one month and planning to download all the courses in between. I will be able to download all the courses? I am asking because otherwise my money will go waste...!!!

**Comment by shihabmridha** [comment]
@aashish1910 You should be able to download all the available courses. But remember, **this software does not come with any guarantee!**

Also, please close the issue if it gets resolved.
