### ISSUE TITLE
Print to pdf not implemented

### ISSUE THREAD

**Issue by Smartman01** [shihabmridha/educative.io-downloader#41]
I am getting an error that says "Reason: Protocol error (Page.printToPDF): PrintToPDF is not implemented"  Which results in nothing being downloaded. Btw I have loginCheck and headless set as false.

**Comment by devKshitijJain** [comment]
When you change headless to false it won't work. It will only work in
headless true mode.

**Comment by itsmeakashgoyal** [comment]
Through this script mhtml files and pdf files are downloading but these are blank. No content is showing there. Kindly help to download the course.

**Comment by devKshitijJain** [comment]
Make headless false and see if you are logged in? Usually this happens when
you are not logged in.

**Comment by Smartman01** [comment]
Ok thank you
