### ISSUE TITLE
Access Denied error

### ISSUE THREAD

**Issue by ajmerainfo** [shihabmridha/educative.io-downloader#45]
I am getting access denied error.

https://www.screencast.com/t/inlA7b5opsm
I have checked the username and the password is working fine on the browser.

**Comment by RahilRehan** [comment]
[2020-05-27T03_30_56_772Z-debug.log](https://github.com/shihabmridha/educative.io-downloader/files/4686319/2020-05-27T03_30_56_772Z-debug.log)
Same error

**Comment by devKshitijJain** [comment]
It generally happens if you are using the script with headless false. Try with headless true.

**Comment by 0psuri** [comment]
Same with headless true; this error is not going

**Comment by uptodate69** [comment]
![image](https://user-images.githubusercontent.com/39705425/83035650-92136980-9fee-11ea-919d-c584b273979b.png)

me too same issue

**Comment by ajmerainfo** [comment]
I have tried everything but could not work. I am using Windows 10.

But for temporary, I found the way to download stuff with setting cookie manually from taking auth cookie from current browser.

![2020-05-27_0805](https://user-images.githubusercontent.com/5574954/83037734-ffc09500-9ff0-11ea-8686-6e1df6df333e.png)

**Comment by ajmerainfo** [comment]
Got the issue. 

if we logged out from the main account everywhere else then it worked.

So only one person can log in at a time.

**Comment by anilchoudhary** [comment]
I've logged out from everywhere, but still getting the same issue.

**Comment by shihabmridha** [comment]
@anilchoudhary I have faced the same issue when in headless mode. Can you try this:
- Remove the data directory.
- Run the app in `headless: false` mode.
