### ISSUE TITLE
Downloaded paged shown as blank page in browser

### ISSUE THREAD

**Issue by sustbird** [shihabmridha/educative.io-downloader#46]
Pages has been downloaded successfully using this nice utility. 
mhtml pages are not blank, seems to have all contents. 
But while opening using browser, pages are blank. Tried with chrome, edge, safari, but same behaviour. Exporting to pdf also result in blank pdf.
Would you please let us know how to view the saved pages?

**Comment by shihabmridha** [comment]
- Verify your login credentials and set loginCheck: true.
- Open browser.ts file and find launchBrowser() and set headless: false to see live actions.
- Make sure you are logged in.

**Comment by sustbird** [comment]
Thank you for your response. I did all those.
The page has been downloaded with contents. The problem is when opening the file with browser, it shows entire page as blank .

```
From: <Saved by Blink>
Snapshot-Content-Location: https://www.educative.io/courses/grokking-dynamic-programming-patterns-for-coding-interviews/m2G1pAq0OO0
Subject: What is Dynamic Programming? - Grokking Dynamic Programming Patterns for Coding Interviews
Date: Sun, 31 May 2020 12:57:27 -0000
MIME-Version: 1.0
Content-Type: multipart/related;
	type="text/html";
	boundary="----MultipartBoundary--iiKKxZzGMD495eYZO5t88p2cpCZF9lPJuvvLbRVMpY----"


------MultipartBoundary--iiKKxZzGMD495eYZO5t88p2cpCZF9lPJuvvLbRVMpY----
Content-Type: text/html
Content-ID: <frame-85E34D7B94E0B5F483E91BC826FE2439@mhtml.blink>
Content-Transfer-Encoding: quoted-printable
Content-Location: https://www.educative.io/courses/grokking-dynamic-programming-patterns-for-coding-interviews/....id...

<!DOCTYPE html><html class=3D"default" dir=3D"ltr" lang=3D"en"><head><meta =

..... rest
```

**Comment by amitfegade121** [comment]
I did the same thing as he mentioned, but when I open this file in chrome or firefox, it shows blank page and If I open a page in Internet Explorer, it is showing only home page with index and If I click on any link... nothing is displayed except header containing, login and Signup links... What is an exact issue?
Are u able to open a file in chrome? Is PDF is also properly downloaded?

**Comment by shihabmridha** [comment]
@amitfegade121 If you see the login/signup button/link after downloading a page then it means that you were not successfully logged in. Unsuccessful login is one of the reasons for downloading a blank page.

**Comment by sustbird** [comment]
It was login problem, now solved.

**Comment by amitfegade121** [comment]
> @amitfegade121 If you see the login/signup button/link after downloading a page then it means that you were not successfully logged in. Unsuccessful login is one of the reasons for downloading a blank page.

Okay but on console It is saying Logged In and It navigates to URL and download files. It would have shown message that Logged In fail...
When I set option headless to false. Browser opens and my login fails, why so? Because my credentials are correct, If I normally logged in It works and I have full access to their content...

It would be great, If you can help in this...
Thanks in advance
