### ISSUE TITLE
How are you guys viewing the files?

### ISSUE THREAD

**Issue by raghav2903** [shihabmridha/educative.io-downloader#48]
Every MHTML document is opening up the index file which when you click on opens the website. Also, the pdf option downloads empty 1Kb pdf files. Am I missing something?

Also, if headless is set to false, it does not login. It seems to log in only when headless is set to true.

**Comment by shihabmridha** [comment]
I have just tested the script. I did work for me without any issues. The blank page issue mostly occurs because of unsuccessful login.

- Remove the data directory
- Check your login credentials
- Try again

**Comment by khatibomar** [comment]
try change your browser , firefox does not support mhtml , use chrome.

**Comment by shihabmridha** [comment]
Closed for no followup.
