### ISSUE TITLE
Not able to Login.

### ISSUE THREAD

**Issue by GD177** [shihabmridha/educative.io-downloader#50]
![error](https://user-images.githubusercontent.com/15930769/85443113-8778cf80-b5ae-11ea-8ca4-ad898a15e960.PNG)

getting this error. Please help.

**Comment by ewayuan** [comment]
yes! same issue here! after I login, the chrome crash

**Comment by shihabmridha** [comment]
@ewayuan Your comment has been deleted for not being reasonable.

**Comment by alexbukvic** [comment]
Hi, have you solved this problem?

**Comment by shihabmridha** [comment]
@alexbukvic As you can see above that, the issue is closed in https://github.com/shihabmridha/educative.io-downloader/commit/201b76d2356c9603f30e68f9b15687e51457d6a5. So yeah. It should work now. See the commit for detail reason.
