### ISSUE TITLE
Can't open or view the mhtml saved files after downloading it

### ISSUE THREAD

**Issue by amrayoub** [shihabmridha/educative.io-downloader#58]
Hi,
I Can't open or view the mhtml saved files after downloading it.

I get a blank page with this message " We use cookies as well as similar tools and technologies to improve your experience and to understand how our site is being used. Review our PRIVACY POLICY to learn more about what cookies we use and how to amend your cookie settings."

![Screenshot 2020-07-26 at 03 42 56](https://user-images.githubusercontent.com/16503306/88469467-2bc59d00-cef2-11ea-8b95-fdd5f8684068.png)

**Comment by devKshitijJain** [comment]
You are not logged in. This is the reason that files are blank.

**Comment by amrayoub** [comment]
By removing data directory. it all works fine now
