### ISSUE TITLE
Event after subscribing all pages are not downloading. 

### ISSUE THREAD

**Issue by nyknstyn** [shihabmridha/educative.io-downloader#6]
Attaching the downloaded folder screenshot

![Screen Shot 2020-04-12 at 7 03 30 PM](https://user-images.githubusercontent.com/31756827/79070032-71b67680-7cf0-11ea-8285-5751c65a2cff.png)

**Comment by nyknstyn** [comment]
Some Details:
First I used credential that didn't have subscription. So only the preview pages were downloading.
Later i changed the config to new credentials with subscription. But still only preview files are downloading.

I think its still logged in with the old credentials.

**Comment by shihabmridha** [comment]
Try removing the `data` directory where chrome stores its browsing informations. It should be located at `ROOT_PATH/data`. Check the `ROOT_PATH` variable.

**Comment by nyknstyn** [comment]
Yes. Deleted the data dir. Working now
