### ISSUE TITLE
No matter what I try I get the same error.

### ISSUE THREAD

**Issue by RahilRehan** [shihabmridha/educative.io-downloader#60]
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'C:\Users\dEnOmInAtOr\Downloads\educative.io-downloader-master\build\src\app.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! educative.io-downloader@1.0.0 start: `node build/src/app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the educative.io-downloader@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dEnOmInAtOr\AppData\Roaming\npm-cache\_logs\2020-07-28T01_43_35_456Z-debug.log

**Comment by RahilRehan** [comment]
Sometimes I also get "login button not found on the page" error too.

**Comment by shihabmridha** [comment]
The cause of this issue is not our script. Instead, you should check if you have properly installed & compiled the project and its dependencies.
