### ISSUE TITLE
Error: Reason: Protocol error (Page.printToPDF): PrintToPDF is not implemented

### ISSUE THREAD

**Issue by mkassm** [shihabmridha/educative.io-downloader#65]
This is an error that appeared in some courses while downloading it as PDF is the headless = false
and I made it true for better pdf generation but it's an empty file in some courses that i still can access to them ...

**Comment by shihabmridha** [comment]
To download PDF you need a headless browser so, you need to headless = true. HTML is more stable than PDF.
If you get an empty page it means you are not logged in.
