### ISSUE TITLE
Paid subscription required to download?

### ISSUE THREAD

**Issue by veluhariharan** [shihabmridha/educative.io-downloader#66]
`You need a subscription to use this`

Does it mean I need to have a paid subscription to leverage this? I have headless mode set to true and still I get blank pdf pages.

I tried to debug by settings the headless mode set to false, then I see an error printToPDF not implemented.

**Comment by shihabmridha** [comment]
Yes, you need a paid subscription. This tool doesn't download any course just for free.

**Comment by veluhariharan** [comment]
Thanks. How about downloading free courses? It doesn't work even for the free courses. Am I missing something trivial?

**Comment by shihabmridha** [comment]
It can download free courses. Possibly you are missing something. You will get `printToPDF not implemented` error in `headless: true` mode. I would suggest you download HTML format.
