### ISSUE TITLE
An error with "Could not log in"

### ISSUE THREAD

**Issue by Jinchul81** [shihabmridha/educative.io-downloader#68]
Thanks for providing a wonderful program! I could download some courses, but there was stuck when downloading a specific lesson. Anyway, I stopped the program and restart again. By the way, when I tried five times, the program throws an exception with "Could not log in". I assumed that my account or my IP was blocked, but they were not related to this problem because I changed my IP on a public cloud VM and also used a different account. However, the problem still happened again and again. Would you please give me a help? Thanks.

**Comment by shihabmridha** [comment]
Can you please post the full error log?

**Comment by shihabmridha** [comment]
Closed for inactivity.
