### ISSUE TITLE
Process doesn't exit after downloading course

### ISSUE THREAD

**Issue by shihabmridha** [shihabmridha/educative.io-downloader#69]
I tried to download [this course](https://www.educative.io/courses/grokking-the-behavioral-interview). Everything went fine but the process never stops. After downloading all the lessons it supposed to console.log **"=> Done"** message and exits the process.

@devdcores I believe it has something to do with your code. Can you please take a look?

**Comment by devdcores** [comment]
okay @shihabmridha will look into it.
