### ISSUE TITLE
Error: No browser initialted yet

### ISSUE THREAD

**Issue by Tuscan-blue** [shihabmridha/educative.io-downloader#81]
### Current problem
![image](https://github.com/shihabmridha/educative.io-downloader/assets/141131070/1fda61a1-fab0-48e1-a443-cdd41755b5a2)
The program falls into an infinite loop.

### Steps to reproduce
1. install typescript cli
2. clone the project and open it
3. `npm install` to install dependencies
4. open config/default.json file to set configurations.
5. `npm run compile`
6. `npm start`

**Comment by shihabmridha** [comment]
The new version of the app is in progress. Will be fixed in #80

**Comment by shihabmridha** [comment]
Closed in #80
